# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runSAX <- function(orgData, segmentSize, alphabetSize, iSAX = FALSE) {
    .Call('rsax_runSAX', PACKAGE = 'rsax', orgData, segmentSize, alphabetSize, iSAX)
}

runNormData <- function(data) {
    .Call('rsax_runNormData', PACKAGE = 'rsax', data)
}

runToPAA <- function(data, segSize) {
    .Call('rsax_runToPAA', PACKAGE = 'rsax', data, segSize)
}

runToSAX <- function(data, brkPtNum) {
    .Call('rsax_runToSAX', PACKAGE = 'rsax', data, brkPtNum)
}

