# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runSAX <- function(orgData, segmentSize, alphabetSize, iSAX = FALSE) {
    .Call('rsax_runSAX', PACKAGE = 'rsax', orgData, segmentSize, alphabetSize, iSAX)
}

eucDis <- function(rawData1, rawData2) {
    .Call('rsax_eucDis', PACKAGE = 'rsax', rawData1, rawData2)
}

minDis <- function(SAXData1, card1, SAXData2, card2, rawDataSize, suppressWarnings = FALSE) {
    .Call('rsax_minDis', PACKAGE = 'rsax', SAXData1, card1, SAXData2, card2, rawDataSize, suppressWarnings)
}

runNormData <- function(data) {
    .Call('rsax_runNormData', PACKAGE = 'rsax', data)
}

runToPAA <- function(data, segSize) {
    .Call('rsax_runToPAA', PACKAGE = 'rsax', data, segSize)
}

runToSAX <- function(data, brkPtNum) {
    .Call('rsax_runToSAX', PACKAGE = 'rsax', data, brkPtNum)
}

testFunc <- function(mtx) {
    invisible(.Call('rsax_testFunc', PACKAGE = 'rsax', mtx))
}

